// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBHX8mXsqcNUkVS9MPhY-AX0Wjm9N4Mm4',
    appId: '1:700273868501:web:2b98ba51bc72b40f33ec5c',
    messagingSenderId: '700273868501',
    projectId: 'ecocollect-app-c57b5',
    authDomain: 'ecocollect-app-c57b5.firebaseapp.com',
    storageBucket: 'ecocollect-app-c57b5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFkuFtACGsZmBM4nRF2TMi0NlAwePxJOg',
    appId: '1:700273868501:android:7c849ddf5527a89833ec5c',
    messagingSenderId: '700273868501',
    projectId: 'ecocollect-app-c57b5',
    storageBucket: 'ecocollect-app-c57b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDszGigGLw7CZ7ShsY3mwMMvTbQrLMgpXw',
    appId: '1:700273868501:ios:7f7a1b63b260be3d33ec5c',
    messagingSenderId: '700273868501',
    projectId: 'ecocollect-app-c57b5',
    storageBucket: 'ecocollect-app-c57b5.firebasestorage.app',
    iosBundleId: 'com.ecocollect.ecocollect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDszGigGLw7CZ7ShsY3mwMMvTbQrLMgpXw',
    appId: '1:700273868501:ios:7f7a1b63b260be3d33ec5c',
    messagingSenderId: '700273868501',
    projectId: 'ecocollect-app-c57b5',
    storageBucket: 'ecocollect-app-c57b5.firebasestorage.app',
    iosBundleId: 'com.ecocollect.ecocollect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBHX8mXsqcNUkVS9MPhY-AX0Wjm9N4Mm4',
    appId: '1:700273868501:web:36f5a645eacc0dcb33ec5c',
    messagingSenderId: '700273868501',
    projectId: 'ecocollect-app-c57b5',
    authDomain: 'ecocollect-app-c57b5.firebaseapp.com',
    storageBucket: 'ecocollect-app-c57b5.firebasestorage.app',
  );
}
